services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass@123
    ports:
      - "1435:1433"

  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    container_name: api-gateway
    ports:
      - "7001:8080"
    depends_on:
      - user-service
      - notes-service
      - labels-service
      - collaborator-service

  user-service:
    build:
      context: .
      dockerfile: src/Services/UserService.API/Dockerfile
    container_name: user-service
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=StrongPass@123;TrustServerCertificate=True;Encrypt=False;

  notes-service:
    build:
      context: .
      dockerfile: src/Services/NotesService/NotesService.API/Dockerfile
    container_name: notes-service
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=StrongPass@123;TrustServerCertificate=True;Encrypt=False;

  labels-service:
    build:
      context: .
      dockerfile: src/Services/LabelsService.API/Dockerfile
    container_name: labels-service
    ports:
      - "5003:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=StrongPass@123;TrustServerCertificate=True;Encrypt=False;

  collaborator-service:
    build:
      context: .
      dockerfile: src/Services/CollaboratorService.API/Dockerfile
    container_name: collaborator-service
    ports:
      - "5004:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=StrongPass@123;TrustServerCertificate=True;Encrypt=False;